# Generated by Django 4.2.6 on 2023-12-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=None, max_length=60),
        ),
    ]
